catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
onlyBuiltDependencies:
  - esbuild
overrides:
  vite@*: "catalog:"
  vitest@*: 5.0.1
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
